@startmindmap
* Teamlead Roadmap
** Роли и обязанности
***_ Resource Manager
***_ Product Owner
***_ Integrator

left side

** Personal Skills
***_ Развитие себя
****_ Умение учиться
****_ Рефлексия
****_ Выработка привычек
***_ Отношения
****_ Эмпатия
****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/self-improvement/emotional-intelligence.md Эмоциональный интеллект]]
****_ Понимание ценности различий
***_ Мышление
****_ Системное мышление
****_ Стратегическое видение
****_ Принятие решений
***_ Стили управления
***_ Коммуникации
***_ Тайм-менеджемент

@endmindmap